AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'Gemfile'

Metrics/BlockLength:
  Max: 30

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

