source 'https://rubygems.org'
gem 'rails', '<5.0'

#gem 'byebug'
gem 'activerecord-tableless'
gem 'camel_snake_keys'

gem 'delayed_paperclip'
gem 'devise-async'

gem 'grape'
gem 'grape-entity'
gem 'grape-kaminari'
gem 'grape-swagger'

gem 'paperclip'
gem 'pundit'

gem 'sqlite3'
