source 'https://rubygems.org'
gem 'rails', '<5.0'

#gem 'byebug'

gem 'grape'
gem 'grape-entity'
gem 'grape-swagger'
gem 'grape-kaminari'

gem 'pundit'
gem 'paperclip'
gem 'delayed_paperclip'
gem 'devise-async'
gem 'activerecord-tableless'

gem 'camel_snake_keys'

gem 'sqlite3'
